# Generated by Django 2.0.13 on 2019-06-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0002_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='n_serie',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
