# Generated by Django 2.0.13 on 2019-06-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0003_equipamento_n_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_OS', models.CharField(max_length=100)),
                ('dataSolicitacao', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('falha', models.CharField(max_length=100)),
                ('grauNecessidade', models.CharField(max_length=100)),
            ],
        ),
    ]
