# Generated by Django 2.0.13 on 2019-06-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0005_auto_20190617_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='empresa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
